feat: add VITE_LIFI_SHOW_TESTNET to env
lifinance/jumper.exchange pull request #506
Opened 2023-04-05 14:11 UTC by dennyscode

Ticket: https://lifi.atlassian.net/browse/LF-2659

Thanks @abhishek-lifi

2023-04-12 02:58 UTC, chybisov commented on packages/dapp/src/components/Widget/Widget.tsx
> +    <LiFiWidget config={widgetConfig} integrator={'testnets-jumper.exchange'} />
We should provide an integrator string based on the MODE variable to have the same code in every branch (testnet/dev/staging/main) without limitations.

2023-04-12 03:00 UTC, chybisov commented on packages/dapp/src/const/MenuConfig/ConnectedMenu/Connected-SubMenu-Chains.tsx
> +  let availableChains = [...chains];
Probably unnecessary. Should be `let availableChains = chains` instead?

2023-04-12 13:32 UTC, Addminus commented on packages/dapp/src/const/MenuConfig/ConnectedMenu/Connected-SubMenu-Chains.tsx
> +  if ((import.meta as any).env.VITE_LIFI_SHOW_TESTNET) {
You could simplify that check by checking the build `mode`. You added `vite --mode testnet` to the package.json scripts

2023-04-12 13:33 UTC, Addminus commented on packages/dapp/.env.testnet
> +VITE_LIFI_SHOW_TESTNET=true
checking for the build mode would remove the need for this env var

2023-04-13 15:24 UTC, Addminus requested changes

2023-04-13 15:24 UTC, Addminus commented on packages/dapp/env.d.ts
> +  BASE_URL: string;
they should be read only, right?

2023-04-13 16:32 UTC, dennyscode commented
Thanks Adrian! I did the fix!

2023-04-14 12:14 UTC, dennyscode commented on packages/dapp/.env.testnet
> +VITE_WIDGET_INTEGRATOR=testnet.jumper.exchange
Is there anything wrong here? It´s not highlighted compared to the other env files.

2023-04-14 12:14 UTC, dennyscode commented on packages/dapp/env.d.ts
> +  readonly SSR: boolean;
Is this unnecessary? Still running into typescript issues on those env´s! 

1.) I guess overwriting such as BASE_URL, DEV, PROD or SSR does not make much sense, right? It is taken from the Vite´s ImportMetaEnv.
2.) But does it make sense to define the MODE types? Or is it bad practise?

Here is the error I wish to get fixed:
![image](https://user-images.githubusercontent.com/43956540/232039859-77a69ca9-17c0-4387-870a-585793e2c19f.png)

2023-04-14 12:14 UTC, dennyscode commented on packages/dapp/env.d.ts
> +  readonly SSR: boolean;
ℹ️ Of course, same applies also the the develop-branch. This PR here is only being merged into the testnet-branch. So, any improvements need to be done to develop as well.

2023-04-17 10:37 UTC, merged