fix: remove showcases section from jumper
lifinance/jumper.exchange pull request #637
Opened 2023-09-08 07:11 UTC by Abhikumar98

<img width="503" alt="CleanShot 2023-09-08 at 16 11 34@2x" src="https://github.com/lifinance/jumper.exchange/assets/35174288/bb8c7e86-603a-4c74-acc8-98c010c494d9">

2023-09-08 07:51 UTC, dennyscode requested changes
Let´s also delete the showcases labels from the english-translation file. 


```
   "developers": {
      "github": "GitHub",
      "documentation": "Documentation",
      ~~"showcases": "Showcases"~~
    },

~~    "showcases": {
      "ukraineDonation": "Support Ukraine 🇺🇦",
      "klimaStaking": "Cross Chain Klima Staking",
      "carbonOffset": "Cross Chain Carbon Offset"
    }~~
```

2023-09-08 07:51 UTC, dennyscode commented on packages/dapp/src/const/MenuConfig/useDevelopersContent.tsx
Two more imports can be deleted from here:

```
import SlideshowIcon from '@mui/icons-material/Slideshow';
import { MenuKeys } from '..';
```

My linter automatically removed it, how come it´s not the case on your machine? Let´s check if it´s properly set up as I had noticed a few times that some Linter-suggestions popped up which might not have been shown to you.

2023-09-08 07:57 UTC, Abhikumar98 commented
> Let´s also delete the showcases labels from the english-translation file.
> 
> ```
>    "developers": {
>       "showcases": "Showcases"
>     },
> 
>     "showcases": {
>       "ukraineDonation": "Support Ukraine 🇺🇦",
>       "klimaStaking": "Cross Chain Klima Staking",
>       "carbonOffset": "Cross Chain Carbon Offset"
>     }
> ```

I was kinda not sure about removing it manually or does it sync with Crownin, hence didn't touch it. Should I go ahead with it?

2023-09-08 07:57 UTC, Abhikumar98 commented on packages/dapp/src/const/MenuConfig/useDevelopersContent.tsx
ahh, got it.
It misses it sometimes when there's a lag. Removing it manually

2023-09-08 08:05 UTC, dennyscode commented
From my understanding: The english-translation file acts as a baseplate. Crowdin picks up on the changes within that file from our repo and represents that list on the Crowdin-platform. So, deleting it here should do no harm and just cleans up our "dictionary" - in code and on our active translations on crowdin.

It´s probably still being cached/saved on our Crowdin account, so whenever we need to use it again, Crowdin will likely recommend us our past translations.

@chybisov Please confirm

2023-09-08 08:16 UTC, chybisov commented
@dennyscode 😄
![ggPUBI0](https://github.com/lifinance/jumper.exchange/assets/18644653/179610b8-c062-4935-b9f6-cceb3dc99347)

2023-09-11 14:32 UTC, dennyscode approved these changes

2023-09-12 08:18 UTC, chybisov approved these changes

2023-09-12 08:18 UTC, merged