chore: refactor the frontends chain list usage (LF-4516)
lifinance/jumper.exchange pull request #652
Opened 2023-09-13 14:03 UTC by dennyscode

Ticket: https://lifi.atlassian.net/browse/LF-4516

2023-09-13 14:04 UTC, dennyscode commented on packages/dapp/src/types/internal.types.ts
> +  chainId: number;
Is this legit? Still not sure about it

2023-09-13 14:05 UTC, dennyscode commented on packages/shared/src/types/multisig.ts
> +  destinationChain?: number;
Same here

2023-09-13 14:09 UTC, dennyscode commented on packages/dapp/src/types/internal.types.ts
> +  chainId: number;
Okay, you said this multiple times, thanks for you patience, will bring this back!

2023-09-13 14:36 UTC, dennyscode commented on packages/dapp/src/types/internal.types.ts
>    'fromChain' | 'requiredUI'
All of that was junk not in use. 
Wallet related stuff was duplicated and should be used from wallet.ts instead, so got rid of what was found in here.

2023-09-14 14:09 UTC, chybisov requested changes

2023-09-14 14:31 UTC, dennyscode commented on packages/dapp/src/types/userTracking.types.ts
> +import { WalletAccount } from '@transferto/shared/src/types';
Created this task:
https://lifi.atlassian.net/browse/LF-4923

2023-09-14 15:02 UTC, chybisov commented on packages/dapp/src/components/Navbar/Menu/WalletMenu/WalletMenu.tsx
> +import { useChains } from '../../../../hooks/useChains';
Also, you know there is something wrong when you need to make `../../../../` imports 😄

2023-09-14 15:03 UTC, chybisov approved these changes

2023-09-22 14:16 UTC, Abhikumar98 approved these changes

2023-09-22 14:23 UTC, merged