feat: add lifi-explorer to dev submenu
lifinance/jumper.exchange pull request #667
Opened 2023-10-02 05:27 UTC by dennyscode

Ticket: https://lifi.atlassian.net/browse/LF-5103

![image](https://github.com/lifinance/jumper.exchange/assets/43956540/c46e277a-30b1-4d26-83e0-25e2090c42eb)

2023-10-02 06:48 UTC, dennyscode commented
There´s a few open questions in the ticket

2023-10-02 07:19 UTC, Addminus requested changes
it makes more sense to add it to the top level of the menu. its not just for devs
<img width="322" alt="image" src="https://github.com/lifinance/jumper.exchange/assets/10106351/943355ac-d21c-4073-b3a7-eba0cb991646">
also it should be `LIFI-Explorer`

2023-10-02 07:42 UTC, dennyscode commented
@Addminus 

1.) Added to top-menu
2.) Renamed to "LI.FI Explorer" (with dot, without "-")

2023-10-02 08:14 UTC, chybisov commented
> @Addminus 
> 
> 
> 
> 1.) Added to top-menu
> 
> 2.) Renamed to "LI.FI Explorer" (with dot, without "-")

Thanks for the second 😅 Came here to say the same 😄

2023-10-02 08:25 UTC, dennyscode commented
@chybisov Thanks for checking in and confirming that!! 👍

2023-10-02 11:24 UTC, chybisov requested changes

2023-10-02 14:26 UTC, dennyscode commented on packages/dapp/src/i18n/en/translation.json
> +      "lifi_explorer": "LI.FI Explorer",
Of course! Thank you, not sure what made me use that snake casing here again 🐍

2023-10-04 10:54 UTC, chybisov approved these changes

2023-10-05 13:30 UTC, merged