Lf 5275 bump arc x version to 2 0
lifinance/jumper.exchange pull request #709
Opened 2023-10-25 03:12 UTC by 0xsebn

Jira: https://lifi.atlassian.net/jira/software/c/projects/LF/boards/15?selectedIssue=LF-5275

Attributes removed since sdk already tracks it on its own

2023-10-25 07:28 UTC, dennyscode requested changes
A couple more ideas I picked up from the docs:

1.) Not fully sure what is being picked up by default and what not. But in the docs it stated, that disconnection will only be picked up by ArcX on Metamask wallet. So, I am tended to:

Adding the "disconnect" function provided by ArcX. We currently do not include it in our "trackDisconnectWallet". Since it relies on the account, I believe we have to make another adjustment.

![image](https://github.com/lifinance/jumper.exchange/assets/43956540/303a7da7-6b66-4792-877c-fce5f2f99702)
![image](https://github.com/lifinance/jumper.exchange/assets/43956540/0c8674c9-3b29-434a-866b-5f8418c5bf3c)

2.) Same with the pageload. Although, it´s doing things straight outta the box, not sure if that applies with the pageload as well. But maybe we can check later on and actually log into the dashboard and test.

Right now, we´re just sending an "event" 
**BUT** actually, all of these "trackPageload" have arc-x disabled in the "disabledTrackingTool" array. So, not really important as it´s not used anyways.

My thought at some point was to send events for internal pages (like on jumper.exchange/something) and use that arcx´s pageload function for external links.

![image](https://github.com/lifinance/jumper.exchange/assets/43956540/c2fe64f5-fc7a-42f6-a6b1-c14ede460de4)

Let´s have a chat later

2023-10-26 18:33 UTC, dennyscode approved these changes

2023-10-27 08:20 UTC, chybisov approved these changes

2023-10-30 08:54 UTC, Addminus requested changes
Actually taking into consideration the upcoming jumper blog, that page tracking would be very interesting! I think we should add it now for internal pages (like denny suggested). implementing a track pageview function for that on useUserTracking would be suitable. Also i noticed the docs had a switch chain function. a new function for tracking that would be nice as well?

2023-10-30 09:50 UTC, dennyscode commented
@Addminus 

1.) Yes, for that blog it´d make sense to have it in place. Currently, we are just not using it at all - but taking that into consideration it could make sense to have it prepared.
2.) On the switch-chain: I am not sure what is being automatically picked up by the SDK-Provider/Wrapper that comes from arcx and what not. Some functions in the past, we had integrated, were already triggered without further code on our end. @0xsebn Since you were chatting with Kerman last, could you check on that part?

2023-11-10 10:43 UTC, dennyscode requested changes
Just that little thing. One more change that just changed recently due to the update of the welcome screen. Thanks for bearing with it! :)

2023-11-10 10:43 UTC, dennyscode commented on packages/dapp/src/components/WelcomeWrapper/WelcomeWrapper.tsx
Those changes applied here, can now go into WelcomeScreen.tsx. Just that minor thing of removing arcx from that disabledTrackingTools array, I would bet.

2023-11-10 19:00 UTC, 0xsebn commented on packages/dapp/src/components/WelcomeWrapper/WelcomeWrapper.tsx
got it, thanks denny :D

2023-11-13 13:19 UTC, dennyscode approved these changes

2023-11-13 14:07 UTC, chybisov requested changes
Not sure why husky didn't manage this, but could you please fix formatting issue like missing spaces 🙂

2023-11-15 10:16 UTC, chybisov approved these changes

2023-11-16 09:44 UTC, Addminus approved these changes

2023-11-16 09:45 UTC, merged