fix: fixed updated signer closure
lifinance/jumper.exchange pull request #712
Opened 2023-10-27 13:56 UTC by Abhikumar98

2023-10-30 13:29 UTC, Abhikumar98 commented
WAITING FOR https://github.com/lifinance/widget/pull/147 Widget PR to be merged and deployed

2023-10-30 13:30 UTC, Addminus requested changes

2023-10-30 13:30 UTC, Addminus commented on packages/dapp/src/components/Navbar/Menu/WalletMenu/WalletMenu.tsx
>      const response = await checkMultisigEnvironment();
choose a clearer name for this response? `isMultisig`

2023-10-30 13:30 UTC, Addminus commented on packages/dapp/src/components/Navbar/Menu/WalletMenu/WalletMenu.tsx
> +  console.log({ isSmartContractWalletEnv });
remove log

2023-10-30 13:32 UTC, Addminus approved these changes

2023-10-30 13:34 UTC, chybisov requested changes

2023-10-30 13:34 UTC, chybisov commented on packages/dapp/src/hooks/useCyberConnectWallet.ts
> +    });
The name should be LI.FI. Can we also not use hard-coded icon links because we will move icons from there soon and they will be broken 🙂

2023-10-30 13:34 UTC, chybisov commented on packages/shared/src/types/wallet.ts
> +  switchChain(chainId: ChainId): Promise<any>;
Why is this any now? Let's type it properly 🙂

2023-11-13 15:21 UTC, chybisov approved these changes

2024-04-24 09:23 UTC, closed without merging