style: apply grid to welcome-screen
lifinance/jumper.exchange pull request #724
Opened 2023-11-20 12:26 UTC by dennyscode

Ticket: https://lifi.atlassian.net/browse/LF-5796

2023-11-22 12:33 UTC, Addminus commented
<img width="290" alt="image" src="https://github.com/lifinance/jumper.exchange/assets/10106351/20d8059d-0523-4ba2-bd3f-01a89708e10b">
on galaxy fold the welcome screen looks like this. iphone 12 pro is similar

2023-11-22 12:41 UTC, chybisov commented
@Addminus tested the latest link on iPhone 14 Pro Max and looks fine in both Safari and Chrome. I'm curious where did you have a chance to test on Galaxy Fold? 😄
![telegram-cloud-photo-size-2-5399846503775850202-y](https://github.com/lifinance/jumper.exchange/assets/18644653/e5879910-608b-4b4a-a91d-a7842aa4f7a1)

2023-11-22 21:45 UTC, KriptoQraf commented
testnet?

2023-11-23 09:30 UTC, Addminus approved these changes

2023-11-23 10:50 UTC, chybisov requested changes

2023-11-23 13:16 UTC, dennyscode commented on packages/dapp/src/components/Widget/Widget.style.ts
> +  [`@media screen and (min-height: 900px)`]: {},
Thanks Eugene! Even found a few more of these! :crossed_swords:

2023-11-27 14:56 UTC, chybisov commented
Small issue

https://github.com/lifinance/jumper.exchange/assets/18644653/cb2bf6a1-c743-4b5d-829e-efa5ce5986b3

2023-11-29 13:33 UTC, chybisov commented on packages/dapp/src/components/Widgets/Widgets.style.tsx
> +export const hoverOffset = '24px';
Where is this used? 🙂

2023-11-29 14:25 UTC, dennyscode commented on packages/dapp/src/components/Widgets/Widgets.style.tsx
> +export const hoverOffset = '24px';
It's removed. Good find!!

2023-11-29 14:27 UTC, chybisov approved these changes

2023-11-30 09:45 UTC, merged