feat: integrate basic blog structure
lifinance/jumper.exchange pull request #742
Opened 2023-12-22 11:17 UTC by dennyscode

Ticket: https://lifi.atlassian.net/browse/LF-6294

2024-01-30 14:29 UTC, dennyscode commented on src/components/BlogArticle/BlogArticle.style.ts
> +  shouldForwardProp: (prop) => prop !== 'backgroundImageUrl',
Good find! Removed it

2024-01-30 14:47 UTC, dennyscode commented on src/Layout.tsx
> +  children?: React.ReactNode;
Makes a lot of sense, yes

2024-01-30 14:50 UTC, dennyscode commented on src/components/AccordionFAQ/AccordionFAQ.tsx
> +        },
Yes, I agree! It was a first shot, but now it´s found a new home in a seperate styled component.

2024-02-28 16:07 UTC, dennyscode commented on src/components/AccordionFAQ/AccordionFAQ.style.ts
This is not being used, but we may have it ready for later usage.

2024-02-28 16:08 UTC, dennyscode commented on src/components/BackgroundGradient/BackgroundGradient.style.tsx
We touched the Background-Gradients and updated it throughout the whole page.

2024-02-28 16:09 UTC, dennyscode commented on src/components/BackgroundGradient/BackgroundGradient.tsx
In addition to the change of current Background-Gradients, we added another type of Background being used on the blog.

2024-02-28 16:12 UTC, dennyscode commented on src/components/Blog/BlogArticlesBoard/BlogArticlesBoard.tsx
This file is currently not in use, but we will likely add it once we have more articles ready

2024-02-28 16:17 UTC, dennyscode commented on src/components/Blog/CustomRichBlocks.tsx
This is actually some magical component with some Voodoo involved. I´d like to hear your thoughts on that
@chybisov @Addminus @0xsebn @DNR500 @tcheee 

-> This turns into our customized blog components such as:
- InstructionsAccordion
- BlogCTA

2024-02-28 16:19 UTC, dennyscode commented on src/components/Button/Button.style.ts
Had to come back to it and clean it up. It´s a first step before moving our button stylings to the actual MUI theme.

2024-02-28 16:22 UTC, dennyscode commented on src/components/IconButton.style.ts
This also is a first step to move our IconButtons to a more re-usable way. Likely, we move this to the MUI theme later

2024-02-28 16:23 UTC, dennyscode commented on src/components/JsonSchema/JsonSchemaQA.tsx
Not used, yet. Likely to be used later (relates to the FAQ)

2024-02-28 16:25 UTC, dennyscode commented on src/components/Menus/MainMenu/useMainMenuContent.tsx
> +      label: 'Jumper Learn',
Is "Jumper Learn" going to be internationalized?

2024-02-28 16:34 UTC, dennyscode commented on src/hooks/useStrapi.ts
This is a first refactoring to move all strapi related stuff into one place. @Addminus Would love to get this more structured

2024-02-29 10:04 UTC, DNR500 commented on src/components/Blog/CustomRichBlocks.tsx
Looks like @strapi/blocks-react-renderer is providing a factory pattern to override some of the RichText rendering which is certainly going to be useful.

Its probably not a problem at the moment but sometimes these factories can get a lot bigger over time - at some point it might be worth looking at how to pull out some things, like CSS etc, to keep the CustomRichBlocks function as succinct and declarative as possible. But maybe we won't add much beyond what is already there. @strapi/blocks-react-renderer looks like a good way to customise the rich text output. :-)

2024-03-04 14:19 UTC, Addminus requested changes

2024-03-04 14:24 UTC, dennyscode commented on src/components/Blog/BlogArticlesBoard/index.ts
> +// export * from './BlogArticlesBoard';
We decided to leave out that "Over view of articles" in the first iteration while we do not have so many articles published, yet.

2024-03-04 14:31 UTC, Addminus approved these changes

2024-03-04 14:34 UTC, tcheee approved these changes
Only tested on the UI and the interaction between pages but it was working well.

2024-03-04 14:47 UTC, chybisov approved these changes

2024-03-04 15:16 UTC, merged