feat: widget v3 alpha
lifinance/jumper.exchange pull request #746
Opened 2023-12-27 16:29 UTC by Addminus

2024-01-25 09:48 UTC, DNR500 commented on src/components/Menus/EcosystemSelectMenu/EVMConnectButton.tsx
> +      //   onNotInstalled(connector);
Is this still needed? If you want to keep this in might be good to add a comment to say why

2024-01-25 09:56 UTC, DNR500 commented on src/components/Widgets/WidgetEvents.tsx
> +  // RouteContactSupport,
Do we need to keep this?

2024-01-25 10:00 UTC, DNR500 commented on src/components/Widgets/WidgetEvents.tsx
> +    // widgetEvents.on(WidgetEvent.RouteContactSupport, onRouteContactSupport);
Again maybe a line to help understand why we are keeping this in?

2024-01-30 07:05 UTC, chybisov requested changes
<img width="424" alt="image" src="https://github.com/lifinance/jumper.exchange/assets/18644653/8ba997cf-0570-4b1b-a51f-4b6892d837e5">


When on a dark theme those borders should have adjusted color to have a cut effect as on a light theme. Also, they look too thick and we should make them a little thinner on both themes.

2024-01-31 05:56 UTC, chybisov commented
@Addminus the above comment can be related to https://github.com/lifinance/jumper.exchange/pull/749

2024-02-01 00:17 UTC, dennyscode commented
@Addminus @chybisov Tweaked just little things to follow along with styling.

Few things to bring up:

1.) Let´s talk again about these wallet logos and check MetaMask which seems to be pretty squeezed into that circle. On Taho it looks good. But please confirm once again, Eugene: We will handle such cases like the MetaMask after we will update logos to make them all fit well, right?

2.) The new wallet-menu looks nice! Good job. But now, seeing this one and clicking through: It feels odd being at the "Select Wallet" menu.
Would it be better to use same typography for "Connect another wallet" and "See all wallets" buttons?
![image](https://github.com/lifinance/jumper.exchange/assets/43956540/853c0f81-a417-46df-8b3f-4e8ce052972f)
![image](https://github.com/lifinance/jumper.exchange/assets/43956540/a14fdd2c-378c-4ee9-9d2a-f662d6fca5ee)

2024-02-01 07:24 UTC, chybisov commented
@dennyscode 

1) Yes, we will update them so they fit nicely.
2) Yes, let's make typography consistent.

2024-02-01 17:15 UTC, chybisov requested changes
@Addminus found one more issue with wallet menu - when you are disconnected it is not possible to see all wallets.

2024-02-01 17:17 UTC, chybisov commented
@Addminus @dennyscode I fixed and released some updates for wallet icons, so it should be better now, especially for MetaMask. We will continue to update more icons soon.

2024-02-01 17:19 UTC, Addminus commented
> @Addminus found one more issue with wallet menu - when you are disconnected it is not possible to see all wallets.

😂 I have a déjà-vue

2024-02-06 11:34 UTC, chybisov commented
@Addminus, we were too optimistic to think that everyone followed the standards 😄 Solflare doesn't automatically inject itself and many others too. I added Solflare manually, let's figure out what else we need to add 🙂 Here is the list https://github.com/anza-xyz/wallet-adapter/tree/master/packages/wallets

So far, I found Phantom and Backpack follow standards.

2024-02-08 09:15 UTC, dennyscode commented
One more bug to be fixed: When connected to SOL, the avatar seems to already come with  chain badge:
![image](https://github.com/lifinance/jumper.exchange/assets/43956540/3dd7a467-0f39-4e12-a625-d87c45fa72d0)

2024-02-08 10:12 UTC, chybisov commented
@dennyscode It is not particularly a bug, more like a shitty icon from Solflare MM Snap 😄 I guess we will need to come up with a workaround for this 🥲

2024-02-12 09:42 UTC, Addminus commented
> @Addminus found one more issue with wallet menu - when you are disconnected it is not possible to see all wallets.

Fixed in last commit

2024-02-12 11:23 UTC, merged