feat: few bug fixes (cursor pointer, arc integration, alerts components)
lifinance/jumper.exchange pull request #843
Opened 2024-03-19 14:59 UTC by tcheee

2024-03-20 01:56 UTC, dennyscode requested changes

2024-03-20 01:56 UTC, dennyscode commented on index.html
> +    />
What´s happening here?

2024-03-20 01:56 UTC, dennyscode commented on index.html
Is there substiantial changes going on here? Or is it mostly linting?

2024-03-20 01:56 UTC, dennyscode commented on src/components/Widgets/Widgets.tsx
> -      )}
Testnet Messagebox removed in favor of the InfoAlert?

2024-03-20 01:56 UTC, dennyscode commented on src/components/Alerts/AlertContainer.tsx
> +  }
Edge case: What´s happening when you are on the testnet with a multisig-wallet and having Solana selected? Is it meant to be that we´ll always just end up showing one of these?

In last design call, we agreed to keep the current "MessageBox" for testnet. How come we are moving this down?

2024-03-20 01:56 UTC, dennyscode commented on .env.development
> -VITE_GATEWAY_API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm90b2NvbF9pZCI6IjFhZmRiZDE2LWM4YjAtNDM0Ny1iOTM2LWI0ODkzMGI2ZTczZCIsInByb3RvY29sX2hhc2giOiIwZmY1ZmY1YmY2Njc5ZGNjZTcwMGUxN2Y3YTUxNmU0YTc
How come we can delete this on development but not across other env´s?

2024-03-20 01:56 UTC, dennyscode commented on src/hooks/useAccounts.ts
> +        address: `${(await combinedWallet.evm.getAccounts())[0]}`,
Nice! We might also adjust that part for the user tracking in regards of arcx. They stated that multiple wallets are sent.

2024-03-20 01:56 UTC, dennyscode commented on src/components/Alerts/SolanaAlert.tsx
> +      active={true}
I don´t get the whole picture, yet. But if we went on like that, you might as well remove the "active" prop at all. But let´s have a chat.

2024-04-04 08:49 UTC, Addminus submitted a review, later dismissed

2024-04-04 09:35 UTC, chybisov commented on index.html
> +    />
Are we sure this is better formatted? 😄

2024-04-24 09:23 UTC, closed without merging