fix: menus on tablet sizes
lifinance/jumper.exchange pull request #855
Opened 2024-03-25 08:58 UTC by dennyscode

Ticket: https://lifi.atlassian.net/browse/LF-7571

[fix-menu-screen-capture.webm](https://github.com/lifinance/jumper.exchange/assets/43956540/c8a00a7c-7dc2-4cc1-b639-16e3ac622bc2)

2024-03-25 15:52 UTC, DNR500 approved these changes

2024-03-26 00:30 UTC, 0xsebn requested changes
Is it possible to use a border radius value from theme? Not sure if we have a specific borderRadius value on theme.shape ? Besides that looks good to me.

2024-03-26 13:47 UTC, tcheee approved these changes
Good for me.

2024-03-26 15:14 UTC, 0xsebn approved these changes

2024-03-27 11:46 UTC, merged