feat: Add feature card exclusions
lifinance/jumper.exchange pull request #907
Opened 2024-04-17 11:36 UTC by oktapodia

2024-04-17 17:29 UTC, tcheee commented on src/components/FeatureCards/FeatureCards.tsx
> +          ) ?? [];
why this "?? []" check if you already look for the `el.attributes.featureCardsExclusions?.data` to be not null in the if condition above?

2024-04-18 07:33 UTC, oktapodia commented on src/hooks/useStrapi.ts
> +    apiUrl.searchParams.set('populate[BackgroundImageDark]', '*');
I would like to filter the fields returned by the featureCardsExclusions to only have the uid and reduce the payload size, strapi does not seem to support indexes number and string at the same selector level.

The syntax above is doing the same as before (just written differently) to get 1 level of the nested object.

I can keep it as it was before but I'll have to remove the fields selector from the `featureCardsExclusions` field

2024-04-18 20:29 UTC, dennyscode approved these changes
This works like a charm!

My testing approach:
a.) Setup
1.) Created some testing cards (#1, #2)
2.) Within card #2 I added the card #1 to the exclusions
b.) Testing
1.) Enter welcome screen to see cards
2.) Close card #1 to have it added to the disabledFeatureCards array in localstorage
3.) Reload the page
4.) No card #2 shown, woohoo!! :)

[feature-card-exclusion-screen-capture.webm](https://github.com/lifinance/jumper.exchange/assets/43956540/aa215cea-cea0-451a-86f8-b402adce5cc5)

2024-04-24 11:03 UTC, tcheee requested changes

2024-04-24 11:03 UTC, tcheee commented on src/components/FeatureCards/FeatureCards.tsx
> +      const excludedFeatureCards = cards?.filter((el, index) => {
@oktapodia please make the same logic for personalized feature cards as well.

2024-05-02 09:38 UTC, merged