fix: sitemap formatting
lifinance/jumper.exchange pull request #946
Opened 2024-05-01 12:04 UTC by dennyscode

Once removing the alternates, formating looks good:

![image](https://github.com/lifinance/jumper.exchange/assets/43956540/1fe58273-566d-4178-a3e4-b58f5690d144)

NextJS introduced alternates to feature multiple language urls within the sitemap in release 14.2:
https://nextjs.org/blog/next-14-2
[Improvement] Support for localization in generated Sitemaps ([PR](https://github.com/vercel/next.js/pull/53765))

For some reason, we end up with funny formatting when using it. This PR is meant to discuss if that is an issue and if it is, should we remove that part?

2024-05-08 13:30 UTC, tcheee commented on src/app/sitemap.ts
> +    // alternates: {
Please add a comment to why we keep it commented in the code

2024-05-08 14:13 UTC, oktapodia requested changes
Always use main production url to avoid bad index

2024-05-09 08:02 UTC, oktapodia approved these changes
LGTM

2024-05-09 11:07 UTC, tcheee approved these changes

2024-05-09 11:07 UTC, merged