feat: enable filtering on dates for general feature cards
lifinance/jumper.exchange pull request #980
Opened 2024-05-17 15:07 UTC by tcheee

2024-05-20 08:15 UTC, oktapodia commented on src/hooks/useStrapi.ts
> +    const currentDate = new Date(Date.now()).toISOString().split('T')[0];
I'd love to use a date formatter instead of this litte hack, but not blocking

2024-05-20 08:15 UTC, oktapodia commented on src/hooks/useStrapi.ts
> +    apiUrl.searchParams.set(
We need to swap to the strapi api soon-ish to make it cleaner and resilient imo

2024-05-20 08:15 UTC, oktapodia approved these changes
LGTM

2024-05-23 11:41 UTC, dennyscode requested changes
Once I set startCampaign (older than date of today) on strapi that Feature-Card is not shown.

2024-05-23 13:19 UTC, dennyscode approved these changes

2024-05-23 13:46 UTC, merged