chore: add redirect for swap, exchange & gas
lifinance/jumper.exchange pull request #984
Opened 2024-05-21 06:09 UTC by dennyscode

Ticket: https://lifi.atlassian.net/browse/LF-8028

2024-05-21 08:21 UTC, tcheee commented on src/middleware.ts
> +    // Redirect to the default gas-tab "/refuel"
let's keep "/gas" rather than "/refuel" @dennyscode

2024-05-22 09:25 UTC, tcheee commented
We should also rename the "refuel" folder in "gas" in this PR

2024-05-22 09:32 UTC, dennyscode commented on src/middleware.ts
> +    return NextResponse.redirect(new URL('/', request.url));
Nice! Thanks for that

2024-05-22 10:55 UTC, tcheee approved these changes

2024-05-23 08:22 UTC, oktapodia requested changes
Just a quick comment

2024-05-23 08:22 UTC, oktapodia commented on next.config.mjs
> +    ];
```suggestion
    return [
      {
        source: '/:lng?/swap',
        destination: '/',
        permanent: true,
      },
      {
        source: '/:lng?/exchange',
        destination: '/',
        permanent: true,
      },
      {
        source: '/:lng?/refuel',
        destination: '/gas',
        permanent: true,
      },
    ];
```

2024-05-23 10:25 UTC, oktapodia approved these changes
LGTM

2024-05-23 10:44 UTC, merged